Fix `golangci-lint config verify` fails
```
Error: Failed to run: Error: Command failed: /home/runner/golangci-lint-1.64.5-linux-amd64/golangci-lint config verify
jsonschema: "linters-settings.testifylint" does not validate with "/properties/linters-settings/properties/testifylint/type": got null, want object
jsonschema: "linters-settings.wrapcheck" does not validate with "/properties/linters-settings/properties/wrapcheck/type": got null, want object
jsonschema: "linters-settings.gofmt" does not validate with "/properties/linters-settings/properties/gofmt/type": got null, want object
Failed executing command with error: the configuration contains invalid elements
, Error: Command failed: /home/runner/golangci-lint-1.64.5-linux-amd64/golangci-lint config verify
jsonschema: "linters-settings.testifylint" does not validate with "/properties/linters-settings/properties/testifylint/type": got null, want object
jsonschema: "linters-settings.wrapcheck" does not validate with "/properties/linters-settings/properties/wrapcheck/type": got null, want object
jsonschema: "linters-settings.gofmt" does not validate with "/properties/linters-settings/properties/gofmt/type": got null, want object
Failed executing command with error: the configuration contains invalid elements

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

https://github.com/sue445/plant_erd/actions/runs/13421719588/job/37495687040?pr=263